# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Neko\PycharmProjects\Fleet_Manuever_Game\BattleshipGameUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainUIWindow(object):
    def setupUi(self, MainUIWindow):
        MainUIWindow.setObjectName("MainUIWindow")
        MainUIWindow.setWindowModality(QtCore.Qt.NonModal)
        MainUIWindow.setEnabled(True)
        MainUIWindow.resize(1201, 1000)
        self.widget = QtWidgets.QWidget(MainUIWindow)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 4, 1, 1)
        self.treeWidgetFleetP2 = QtWidgets.QTreeWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidgetFleetP2.sizePolicy().hasHeightForWidth())
        self.treeWidgetFleetP2.setSizePolicy(sizePolicy)
        self.treeWidgetFleetP2.setObjectName("treeWidgetFleetP2")
        self.gridLayout.addWidget(self.treeWidgetFleetP2, 3, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem9, 4, 3, 1, 1)
        self.treeWidgetFleetP1 = QtWidgets.QTreeWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidgetFleetP1.sizePolicy().hasHeightForWidth())
        self.treeWidgetFleetP1.setSizePolicy(sizePolicy)
        self.treeWidgetFleetP1.setObjectName("treeWidgetFleetP1")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetFleetP1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidgetFleetP1)
        self.gridLayout.addWidget(self.treeWidgetFleetP1, 1, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem10, 4, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem11, 0, 1, 1, 1)
        self.groupBoxPlayfieldP2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPlayfieldP2.sizePolicy().hasHeightForWidth())
        self.groupBoxPlayfieldP2.setSizePolicy(sizePolicy)
        self.groupBoxPlayfieldP2.setObjectName("groupBoxPlayfieldP2")
        self.gridLayout.addWidget(self.groupBoxPlayfieldP2, 3, 1, 1, 1)
        self.groupBoxPlayfieldP1 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPlayfieldP1.sizePolicy().hasHeightForWidth())
        self.groupBoxPlayfieldP1.setSizePolicy(sizePolicy)
        self.groupBoxPlayfieldP1.setObjectName("groupBoxPlayfieldP1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxPlayfieldP1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_2.addWidget(self.toolButton_5, 1, 1, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_6.sizePolicy().hasHeightForWidth())
        self.toolButton_6.setSizePolicy(sizePolicy)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout_2.addWidget(self.toolButton_6, 1, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_2.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_2.addWidget(self.toolButton_3, 0, 2, 1, 1)
        
        
        class toolButton(QtWidgets.QToolButton):
            def __init__(self, parent=None):
                QtWidgets.QToolButton.__init__(self, parent)
                policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                policy.setHeightForWidth(True)
                self.setSizePolicy(policy)



            def heightForWidth(self, width):
                return width




        self.toolButton = toolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setObjectName("toolButton")
        
        
        
        self.gridLayout_2.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_2.addWidget(self.toolButton_4, 1, 0, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_7.sizePolicy().hasHeightForWidth())
        self.toolButton_7.setSizePolicy(sizePolicy)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_2.addWidget(self.toolButton_7, 2, 0, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_8.sizePolicy().hasHeightForWidth())
        self.toolButton_8.setSizePolicy(sizePolicy)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_2.addWidget(self.toolButton_8, 2, 1, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.groupBoxPlayfieldP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout_2.addWidget(self.toolButton_9, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBoxPlayfieldP1, 1, 1, 1, 1)
        MainUIWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(MainUIWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1201, 21))
        self.menubar.setObjectName("menubar")
        self.menuJoin_Game = QtWidgets.QMenu(self.menubar)
        self.menuJoin_Game.setObjectName("menuJoin_Game")
        self.menuHost_Game = QtWidgets.QMenu(self.menubar)
        self.menuHost_Game.setObjectName("menuHost_Game")
        self.menuQuit_Game = QtWidgets.QMenu(self.menubar)
        self.menuQuit_Game.setObjectName("menuQuit_Game")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainUIWindow.setMenuBar(self.menubar)
        self.actionChange_Playfield_Size = QtWidgets.QAction(MainUIWindow)
        self.actionChange_Playfield_Size.setObjectName("actionChange_Playfield_Size")
        self.actionInfo = QtWidgets.QAction(MainUIWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuSettings.addAction(self.actionChange_Playfield_Size)
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuJoin_Game.menuAction())
        self.menubar.addAction(self.menuHost_Game.menuAction())
        self.menubar.addAction(self.menuQuit_Game.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainUIWindow)
        QtCore.QMetaObject.connectSlotsByName(MainUIWindow)

    def retranslateUi(self, MainUIWindow):
        _translate = QtCore.QCoreApplication.translate
        MainUIWindow.setWindowTitle(_translate("MainUIWindow", "Nico\'s Fleet Manuever Game!"))
        self.treeWidgetFleetP2.headerItem().setText(0, _translate("MainUIWindow", "Ship"))
        self.treeWidgetFleetP2.headerItem().setText(1, _translate("MainUIWindow", "Status"))
        self.treeWidgetFleetP1.headerItem().setText(0, _translate("MainUIWindow", "Ship"))
        self.treeWidgetFleetP1.headerItem().setText(1, _translate("MainUIWindow", "Status"))
        __sortingEnabled = self.treeWidgetFleetP1.isSortingEnabled()
        self.treeWidgetFleetP1.setSortingEnabled(False)
        self.treeWidgetFleetP1.topLevelItem(0).setText(0, _translate("MainUIWindow", "Destroyer_1"))
        self.treeWidgetFleetP1.topLevelItem(0).setText(1, _translate("MainUIWindow", "Alive"))
        self.treeWidgetFleetP1.topLevelItem(1).setText(0, _translate("MainUIWindow", "Destroyer_2"))
        self.treeWidgetFleetP1.topLevelItem(1).setText(1, _translate("MainUIWindow", "Alive"))
        self.treeWidgetFleetP1.setSortingEnabled(__sortingEnabled)
        self.groupBoxPlayfieldP2.setTitle(_translate("MainUIWindow", "GroupBox"))
        self.groupBoxPlayfieldP1.setTitle(_translate("MainUIWindow", "GroupBox"))
        self.toolButton_5.setText(_translate("MainUIWindow", "..."))
        self.toolButton_6.setText(_translate("MainUIWindow", "..."))
        self.toolButton_2.setText(_translate("MainUIWindow", "..."))
        self.toolButton_3.setText(_translate("MainUIWindow", "..."))
        self.toolButton.setText(_translate("MainUIWindow", "..."))
        self.toolButton_4.setText(_translate("MainUIWindow", "..."))
        self.toolButton_7.setText(_translate("MainUIWindow", "..."))
        self.toolButton_8.setText(_translate("MainUIWindow", "..."))
        self.toolButton_9.setText(_translate("MainUIWindow", "..."))
        self.menuJoin_Game.setTitle(_translate("MainUIWindow", "Join Game"))
        self.menuHost_Game.setTitle(_translate("MainUIWindow", "Host Game"))
        self.menuQuit_Game.setTitle(_translate("MainUIWindow", "Quit Game"))
        self.menuSettings.setTitle(_translate("MainUIWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainUIWindow", "Help"))
        self.actionChange_Playfield_Size.setText(_translate("MainUIWindow", "Change Playfield Size"))
        self.actionInfo.setText(_translate("MainUIWindow", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUIWindow = QtWidgets.QMainWindow()
    ui = Ui_MainUIWindow()
    ui.setupUi(MainUIWindow)
    MainUIWindow.show()
    sys.exit(app.exec_())
